version : 0.0
os : linux

files :
  - source : /Files/index.html
    destination : /var/www/html/

hooks :
  ApplicationStop :
    - location : Scripts/stopserver.sh
      timeout : 300
  BeforeInstall :
    - location : Scripts/installserver.sh
      timeout : 300
    - location : Scripts/deregister_from_elb.sh
      timeout : 300
  AfterInstall :
      - location : Scripts/startserver.sh
        timeout : 300
      - location : Scripts/register_with_elb.sh
        timeout : 300
